version: '3.9'
services:
  ssh.cyrhades.com:
    build: ssh
  webssh.cyrhades.com:
    build: webssh
    ports:
    - "80:8888"
  chip-and-fish.cyrhades.com:
    image: anssi/fcsc2021-misc-chip-and-fish:latest
    ports:
      - "4000:4000"
